# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/ColorThiefSwift.xcworkspace -scheme ColorThiefSwift-Example -sdk iphonesimulator10.3 -destination 'id=3684320E-8A74-42B8-82A7-099B0B40601C,platform=iOS Simulator,OS=10.3' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
